name: Test

on:
  push:
    paths-ignore:
      - "docs/**"
      - "*.md"

  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox

      - name: Unit tests
        if: "!startsWith(matrix.python-version, 'pypy')"
        run:
          tox -e ci-py$(echo ${{ matrix.python-version }} | tr -d '.') -- -v --color=yes

      - name: Unit tests (pypy)
        if: "startsWith(matrix.python-version, 'pypy')"
        run: tox -e ci-pypy3 -- -v --color=yes
